# Aymane 06-12-24
print("---------------------------------- START ----------------------------------")
print("Esercizio 1")
print("\tChiedi all'utente di inserire una parola e stampa il numero di caratteri della parola.")
# Prendo in input e calcolo direttamente
print("\t[Dim]:", len(input("\tWord: ")))
print("---------------------------------------------------------------------------")
print("Esercizio 2")
print("\tChiedi all'utente di inserire due numeri, calcola il loro quoziente e stampa il risultato.")
num1 = float(input("\tNumero 1: "))
num2 = float(input("\tNumero 2: "))
print(f"\t{num1} / {num2} = {num1/num2}")
print("---------------------------------------------------------------------------")
print("Esercizio 3")
print("\tChiedi all'utente di inserire una parola e stampa la parola con i caratteri alternati in maiuscolo e minuscolo.")
parola = input("\tInserire parola: ")
new_parola = "".join(carattere.upper() if indice % 2 == 0 else carattere.lower() for indice, carattere in enumerate(parola))
print("\tParola modificata: " + new_parola)
print("---------------------------------------------------------------------------")
print("Esercizio 4")
print("\tChiedi all'utente di inserire una frase e stampa il numero di caratteri della frase.")
frase = input("\tInserire frase: ")
print(f"\tLa frase contiene {len(frase)} caratteri.")
print("---------------------------------------------------------------------------")
print("Esercizio 5")
print("\tChiedi all'utente due numeri, calcola la loro potenza (il primo elevato al secondo) e stampa il risultato.")
base = float(input("\tBase: "))
esponente = float(input("\tEsponente: "))
print(f"\t{base}^{esponente} = {base ** esponente}")
print("---------------------------------------------------------------------------")
print("Esercizio 6")
print("\tChiedi all'utente di inserire una parola e stampa la parola con le prime 3 lettere maiuscole e il resto minuscolo.")
parola = input("\tInserisci parola: ")
print(f"\tParola modificata: {parola[:3].upper() + parola[3:].lower()}")
print("----------------------------------- END -----------------------------------")